"""Generate the Windows VERSIONINFO resource for the frozen serp3d.exe.

PyInstaller embeds this as the binary's version resource, which is what
populates file Properties, Task Manager and the installer's publisher fields.
SignPath enforces ProductName and ProductVersion at signing time, so both are
derived from serpentine3d.__version__ rather than written by hand — a release
cannot ship metadata that disagrees with the package.

The spec calls main() at build time; nothing generated here is committed.
"""
import re
import sys
from pathlib import Path

COMPANY = "Chisomo Banzi"
PRODUCT = "Serpentine3D"
DESCRIPTION = "Serpentine3D - NURBS surface modeller"
COPYRIGHT = "MIT Licensed. Copyright (c) Chisomo Banzi."
OUTPUT = Path(__file__).with_name("file_version_info.txt")

_TEMPLATE = """\
# Generated by make_version_info.py - do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vers},
    prodvers={vers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', '{company}'),
        StringStruct('FileDescription', '{description}'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'serp3d'),
        StringStruct('LegalCopyright', '{copyright}'),
        StringStruct('OriginalFilename', 'serp3d.exe'),
        StringStruct('ProductName', '{product}'),
        StringStruct('ProductVersion', '{version}')])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """Turn a PEP 440-ish version into the 4 ints Windows requires.

    Windows wants exactly four numbers, so a three-part version pads with a
    trailing zero and any suffix ("0.6.0rc1") contributes only its digits.
    """
    parts = []
    for chunk in version.lstrip("vV").split("."):
        match = re.match(r"\d+", chunk)
        parts.append(int(match.group()) if match else 0)
    padded = (parts + [0, 0, 0, 0])[:4]
    return tuple(padded)  # type: ignore[return-value]


def version_info(version: str) -> str:
    """Render the VERSIONINFO resource for `version`."""
    return _TEMPLATE.format(
        vers=version_tuple(version),
        version=version,
        company=COMPANY,
        product=PRODUCT,
        description=DESCRIPTION,
        copyright=COPYRIGHT,
    )


def main() -> Path:
    """Write the resource next to the spec and return its path."""
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
    from serpentine3d import __version__

    OUTPUT.write_text(version_info(__version__), encoding="utf-8")
    return OUTPUT


if __name__ == "__main__":
    print(main())
