blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/chisomobanzi/Serpentine3D/discussions
    about: Not sure it's a bug? Want to talk about direction? Start here.
