"""FBX import / export — pure Python, mesh-based.

Serpentine3D is a BREP modeller; FBX is a mesh/scene format, so this mirrors
the OBJ path: export tessellates each shape and writes a *binary* FBX (v7.4);
import parses both binary and ASCII FBX and returns MeshShape objects.

Export is binary because Blender refuses ASCII FBX outright ("ASCII FBX files
are not supported"), while binary is imported by Blender/Maya/Unreal/Unity.
An ASCII writer (`_ascii_doc`/`_write_ascii_geometry`) is retained to exercise
the ASCII reader in tests.
"""

from __future__ import annotations

import struct
import zlib

import numpy as np

from ..core.mesh import MeshShape
from ..core.tessellate import tessellate

_MAGIC = b"Kaydara FBX Binary  \x00\x1a\x00"


def _safe(name: str) -> str:
    return "".join(c if c.isalnum() or c in "_-." else "_" for c in name) or "obj"


# ----------------------------------------------------------------- export
def _poly_indices_from_tris(tris) -> list[int]:
    """Flat FBX PolygonVertexIndex from triangles: the last index of each
    polygon is XOR-terminated (~i == -i-1)."""
    out: list[int] = []
    for a, b, c in np.asarray(tris, np.int64):
        out += [int(a), int(b), -int(c) - 1]
    return out


def _fmt_floats(arr) -> str:
    return ",".join(f"{x:.6g}" for x in np.asarray(arr, float).reshape(-1))


def _ascii_doc(geoms) -> str:
    """geoms: [(name, verts(Nx3), poly_indices(flat, XOR-term),
    pv_normals(Mx3) or None, color or None)]."""
    ng = len(geoms)
    L = ["; FBX 7.4.0 project file",
         "; Generated by Serpentine3D", "",
         "FBXHeaderExtension:  {",
         "\tFBXHeaderVersion: 1003", "\tFBXVersion: 7400",
         '\tCreator: "Serpentine3D"', "}",
         "GlobalSettings:  {", "\tVersion: 1000", "\tProperties70:  {",
         '\t\tP: "UpAxis", "int", "Integer", "",2',
         '\t\tP: "UpAxisSign", "int", "Integer", "",1',
         '\t\tP: "FrontAxis", "int", "Integer", "",1',
         '\t\tP: "FrontAxisSign", "int", "Integer", "",1',
         '\t\tP: "CoordAxis", "int", "Integer", "",0',
         '\t\tP: "CoordAxisSign", "int", "Integer", "",1',
         '\t\tP: "UnitScaleFactor", "double", "Number", "",1', "\t}", "}",
         "Documents:  {", "\tCount: 1",
         '\tDocument: 100000000, "Scene", "Scene" {',
         "\t\tRootNode: 0", "\t}", "}",
         "Definitions:  {", "\tVersion: 100", f"\tCount: {ng * 3}",
         '\tObjectType: "Geometry" {', f"\t\tCount: {ng}", "\t}",
         '\tObjectType: "Model" {', f"\t\tCount: {ng}", "\t}",
         '\tObjectType: "Material" {', f"\t\tCount: {ng}", "\t}", "}",
         "Objects:  {"]
    conns = ["Connections:  {"]
    gid = 1000000
    for i, (name, verts, poly, pvn, color) in enumerate(geoms):
        g, m, mat = gid, gid + 1, gid + 2
        gid += 3
        L.append(f'\tGeometry: {g}, "Geometry::{name}", "Mesh" {{')
        v = np.asarray(verts, float).reshape(-1)
        L.append(f"\t\tVertices: *{v.size} {{")
        L.append(f"\t\t\ta: {_fmt_floats(v)}")
        L.append("\t\t}")
        L.append(f"\t\tPolygonVertexIndex: *{len(poly)} {{")
        L.append("\t\t\ta: " + ",".join(str(int(x)) for x in poly))
        L.append("\t\t}")
        if pvn is not None:
            n = np.asarray(pvn, float).reshape(-1)
            L += ["\t\tLayerElementNormal: 0 {", "\t\t\tVersion: 101",
                  '\t\t\tName: ""',
                  '\t\t\tMappingInformationType: "ByPolygonVertex"',
                  '\t\t\tReferenceInformationType: "Direct"',
                  f"\t\t\tNormals: *{n.size} {{",
                  f"\t\t\t\ta: {_fmt_floats(n)}", "\t\t\t}", "\t\t}",
                  "\t\tLayer: 0 {", "\t\t\tVersion: 100",
                  "\t\t\tLayerElement:  {",
                  '\t\t\t\tType: "LayerElementNormal"', "\t\t\t\tTypedIndex: 0",
                  "\t\t\t}", "\t\t}"]
        L.append("\t}")
        L += [f'\tModel: {m}, "Model::{name}", "Mesh" {{', "\t\tVersion: 232",
              "\t\tProperties70:  {",
              '\t\t\tP: "DefaultAttributeIndex", "int", "Integer", "",0',
              "\t\t}", "\t}"]
        col = color if color is not None else (0.72, 0.72, 0.72)
        L += [f'\tMaterial: {mat}, "Material::{name}", "" {{',
              "\t\tVersion: 102", '\t\tShadingModel: "phong"',
              "\t\tProperties70:  {",
              f'\t\t\tP: "DiffuseColor", "Color", "", "A",'
              f'{col[0]:.4g},{col[1]:.4g},{col[2]:.4g}', "\t\t}", "\t}"]
        conns += [f'\tC: "OO",{g},{m}', f'\tC: "OO",{m},0',
                  f'\tC: "OO",{mat},{m}']
    L.append("}")
    conns.append("}")
    return "\n".join(L + conns) + "\n"


def export_fbx(named_shapes, path: str):
    """named_shapes: [(name, shape)] or [(name, shape, color)]."""
    geoms = []
    for entry in named_shapes:
        name, shape = entry[0], entry[1]
        color = entry[2] if len(entry) > 2 else None
        mesh = tessellate(shape)
        if not mesh.has_faces:
            continue
        tris = np.asarray(mesh.triangles, np.int64)
        poly = _poly_indices_from_tris(tris)
        pvn = (np.asarray(mesh.normals, float)[tris.reshape(-1)]
               if len(mesh.normals) else None)
        geoms.append((_safe(name), np.asarray(mesh.vertices, float),
                      poly, pvn, color))
    _write_fbx(path, geoms)                # binary: Blender rejects ASCII FBX


def _write_ascii_geometry(path, name, verts, poly_indices, normals=None):
    """Minimal single-mesh ASCII FBX with raw (already XOR-terminated)
    polygon indices — used by tests."""
    with open(path, "w", encoding="utf-8") as f:
        f.write(_ascii_doc([(_safe(name), np.asarray(verts, float),
                             list(poly_indices), normals, None)]))


# --------------------------------------------------------------- import
def _triangulate(poly) -> list[tuple[int, int, int]]:
    tris, face = [], []
    for idx in poly:
        idx = int(idx)
        if idx < 0:                      # XOR terminator ends the polygon
            face.append(-idx - 1)
            for k in range(1, len(face) - 1):
                tris.append((face[0], face[k], face[k + 1]))
            face = []
        else:
            face.append(idx)
    return tris


def import_fbx(path: str):
    """Returns [(name, MeshShape)]."""
    with open(path, "rb") as f:
        data = f.read()
    raw = (_read_binary(data) if data[:20] == _MAGIC[:20]
           else _read_ascii(data.decode("utf-8", "replace")))
    out = []
    for name, verts, poly in raw:
        tris = _triangulate(poly)
        verts = np.asarray(verts, float)
        if len(verts) and tris:
            out.append((name, MeshShape(verts, np.asarray(tris, np.uint32))))
    return out


def _read_ascii(text: str):
    import re
    names = re.findall(r'Geometry:\s*\d+\s*,\s*"Geometry::([^"]*)"', text)
    vtx = re.findall(r'Vertices:\s*\*\d+\s*\{\s*a:\s*([-0-9.eE,\s]+?)\s*\}', text)
    idx = re.findall(
        r'PolygonVertexIndex:\s*\*\d+\s*\{\s*a:\s*([-0-9,\s]+?)\s*\}', text)
    out = []
    for i, vtext in enumerate(vtx):
        name = names[i] if i < len(names) else f"mesh{i}"
        verts = np.array([float(x) for x in vtext.replace("\n", " ").split(",")
                          if x.strip()]).reshape(-1, 3)
        poly = ([int(x) for x in idx[i].replace("\n", " ").split(",")
                 if x.strip()] if i < len(idx) else [])
        out.append((name, verts, poly))
    return out


# ----- binary --------------------------------------------------------------
def _read_prop(data, pos):
    t = chr(data[pos]); pos += 1
    if t == "Y":
        v = struct.unpack("<h", data[pos:pos + 2])[0]; pos += 2
    elif t == "C":
        v = bool(data[pos]); pos += 1
    elif t == "I":
        v = struct.unpack("<i", data[pos:pos + 4])[0]; pos += 4
    elif t == "F":
        v = struct.unpack("<f", data[pos:pos + 4])[0]; pos += 4
    elif t == "D":
        v = struct.unpack("<d", data[pos:pos + 8])[0]; pos += 8
    elif t == "L":
        v = struct.unpack("<q", data[pos:pos + 8])[0]; pos += 8
    elif t in ("S", "R"):
        n = struct.unpack("<I", data[pos:pos + 4])[0]; pos += 4
        raw = data[pos:pos + n]; pos += n
        v = raw.decode("utf-8", "replace") if t == "S" else raw
    elif t in ("f", "d", "l", "i", "b"):
        alen, enc, clen = struct.unpack("<III", data[pos:pos + 12]); pos += 12
        raw = data[pos:pos + clen]; pos += clen
        if enc == 1:
            raw = zlib.decompress(raw)
        dt = {"f": "<f4", "d": "<f8", "l": "<i8", "i": "<i4", "b": "<i1"}[t]
        v = np.frombuffer(raw, dtype=np.dtype(dt), count=alen)
    else:
        raise ValueError(f"FBX: unknown property type {t!r}")
    return v, pos


def _read_binary(data):
    ver = struct.unpack("<I", data[23:27])[0]
    v75 = ver >= 7500
    hdr, null = (24, 25) if v75 else (12, 13)

    def read_node(pos):
        if v75:
            end, nprops, _ = struct.unpack("<QQQ", data[pos:pos + 24])
        else:
            end, nprops, _ = struct.unpack("<III", data[pos:pos + 12])
        pos += hdr
        namelen = data[pos]; pos += 1
        if end == 0:                      # null record
            return None, pos + (null - hdr - 1)
        name = data[pos:pos + namelen].decode("utf-8", "replace"); pos += namelen
        props = []
        for _ in range(nprops):
            v, pos = _read_prop(data, pos)
            props.append(v)
        children = []
        while pos < end:
            node, pos = read_node(pos)
            if node is None:
                break
            children.append(node)
        return {"name": name, "props": props, "children": children}, end

    nodes, pos = [], 27
    while pos < len(data):
        node, pos = read_node(pos)
        if node is None:
            break
        nodes.append(node)

    out = []

    def walk(node):
        if node["name"] == "Geometry":
            name, verts, idx = "mesh", None, None
            for p in node["props"]:
                if not isinstance(p, str):
                    continue
                if "\x00\x01" in p:          # binary form: "name\x00\x01Geometry"
                    name = p.split("\x00\x01", 1)[0]
                elif p.startswith("Geometry::"):   # ascii form
                    name = p.split("::", 1)[1]
            for c in node["children"]:
                if c["name"] == "Vertices" and c["props"] is not None:
                    verts = np.asarray(c["props"][0], float).reshape(-1, 3)
                elif c["name"] == "PolygonVertexIndex" and c["props"] is not None:
                    idx = np.asarray(c["props"][0]).astype(np.int64).tolist()
            if verts is not None and idx is not None:
                out.append((name, verts, idx))
        for c in node["children"]:
            walk(c)

    for n in nodes:
        walk(n)
    return out


def _ser_prop(tag, val):
    if tag == "L":
        return b"L" + struct.pack("<q", int(val))
    if tag == "I":
        return b"I" + struct.pack("<i", int(val))
    if tag == "D":
        return b"D" + struct.pack("<d", float(val))
    if tag == "S":
        b = val.encode("utf-8")
        return b"S" + struct.pack("<I", len(b)) + b
    if tag in ("d", "i", "l", "f"):
        dt = {"d": "<f8", "i": "<i4", "l": "<i8", "f": "<f4"}[tag]
        arr = np.asarray(val, dtype=np.dtype(dt))
        raw = arr.tobytes()
        return tag.encode() + struct.pack("<III", arr.size, 0, len(raw)) + raw
    raise ValueError(f"FBX: cannot serialize prop {tag!r}")


def _ser_node(node, start):
    name, props, children = node
    nb = name.encode("utf-8")
    pb = b"".join(_ser_prop(t, v) for t, v in props)
    hsize = 13 + len(nb)                  # v7.4: 3*uint32 + 1 + name
    child_start = start + hsize + len(pb)
    if children:
        cb = b""
        pos = child_start
        for ch in children:
            b, pos = _ser_node(ch, pos)
            cb += b
        cb += b"\x00" * 13                # terminating null record
        pos += 13
    else:
        cb, pos = b"", child_start
    end = pos
    header = (struct.pack("<III", end, len(props), len(pb))
              + bytes([len(nb)]) + nb)
    return header + pb + cb, end


_FOOT_MAGIC = bytes([0xf8, 0x5a, 0x8c, 0x6a, 0xde, 0xf5, 0xd9, 0x7e,
                     0xec, 0xe9, 0x0c, 0xe3, 0x75, 0x05, 0xa8, 0x49])


def _p(name, typ, sub, flags, *vals):
    """A Properties70 'P' entry."""
    props = [("S", name), ("S", typ), ("S", sub), ("S", flags)]
    for v in vals:
        props.append(("D", v) if isinstance(v, float)
                     else ("I", v) if isinstance(v, int) else ("S", str(v)))
    return ("P", props, [])


def _build_document(geoms):
    """Full FBX node tree (geoms: [(name, verts, poly, pvn, color)])."""
    ng = len(geoms)
    top = [
        ("FBXHeaderExtension", [], [
            ("FBXHeaderVersion", [("I", 1003)], []),
            ("FBXVersion", [("I", 7400)], []),
            ("Creator", [("S", "Serpentine3D")], []),
        ]),
        ("GlobalSettings", [], [
            ("Version", [("I", 1000)], []),
            ("Properties70", [], [
                # Serpentine is Z-up (CAD convention); declare the Z-up axis
                # system (as 3ds Max does) so importers preserve orientation
                # instead of rotating our data as if it were Y-up.
                _p("UpAxis", "int", "Integer", "", 2),
                _p("UpAxisSign", "int", "Integer", "", 1),
                _p("FrontAxis", "int", "Integer", "", 1),
                _p("FrontAxisSign", "int", "Integer", "", -1),
                _p("CoordAxis", "int", "Integer", "", 0),
                _p("CoordAxisSign", "int", "Integer", "", 1),
                # 100 = model units are cm-equivalents, so importers that map
                # FBX cm -> their own metres bring geometry back 1:1 (Blender
                # otherwise shrinks it 100x).
                _p("UnitScaleFactor", "double", "Number", "", 100.0),
                _p("OriginalUnitScaleFactor", "double", "Number", "", 100.0),
            ]),
        ]),
        ("Documents", [], [
            ("Count", [("I", 1)], []),
            ("Document", [("L", 100000000), ("S", "Scene"), ("S", "Scene")], [
                ("RootNode", [("I", 0)], []),
            ]),
        ]),
        ("Definitions", [], [
            ("Version", [("I", 100)], []),
            ("Count", [("I", ng * 3)], []),
            ("ObjectType", [("S", "Geometry")], [("Count", [("I", ng)], [])]),
            ("ObjectType", [("S", "Model")], [("Count", [("I", ng)], [])]),
            ("ObjectType", [("S", "Material")], [("Count", [("I", ng)], [])]),
        ]),
    ]
    obj_children, conns = [], []
    gid = 1000000
    for name, verts, poly, pvn, color in geoms:
        g, m, mat = gid, gid + 1, gid + 2
        gid += 3
        v = np.asarray(verts, float).reshape(-1)
        gc = [("Vertices", [("d", v)], []),
              ("PolygonVertexIndex", [("i", poly)], [])]
        if pvn is not None:
            n = np.asarray(pvn, float).reshape(-1)
            gc += [("LayerElementNormal", [("I", 0)], [
                        ("Version", [("I", 101)], []),
                        ("Name", [("S", "")], []),
                        ("MappingInformationType",
                         [("S", "ByPolygonVertex")], []),
                        ("ReferenceInformationType", [("S", "Direct")], []),
                        ("Normals", [("d", n)], [])]),
                   ("Layer", [("I", 0)], [
                        ("Version", [("I", 100)], []),
                        ("LayerElement", [], [
                            ("Type", [("S", "LayerElementNormal")], []),
                            ("TypedIndex", [("I", 0)], [])])])]
        # Binary FBX encodes object names as "name\x00\x01Class" (not the
        # ASCII "Class::name" form); Blender's importer splits on \x00\x01.
        obj_children.append((
            "Geometry", [("L", g), ("S", f"{name}\x00\x01Geometry"),
                         ("S", "Mesh")], gc))
        obj_children.append((
            "Model", [("L", m), ("S", f"{name}\x00\x01Model"), ("S", "Mesh")],
            [("Version", [("I", 232)], []),
             ("Properties70", [], [
                 _p("DefaultAttributeIndex", "int", "Integer", "", 0)])]))
        col = color if color is not None else (0.72, 0.72, 0.72)
        obj_children.append((
            "Material", [("L", mat), ("S", f"{name}\x00\x01Material"),
                         ("S", "")],
            [("Version", [("I", 102)], []),
             ("ShadingModel", [("S", "phong")], []),
             ("Properties70", [], [
                 _p("DiffuseColor", "Color", "", "A",
                    float(col[0]), float(col[1]), float(col[2]))])]))
        conns += [("C", [("S", "OO"), ("L", g), ("L", m)], []),
                  ("C", [("S", "OO"), ("L", m), ("L", 0)], []),
                  ("C", [("S", "OO"), ("L", mat), ("L", m)], [])]
    top.append(("Objects", [], obj_children))
    top.append(("Connections", [], conns))
    return top


def _write_fbx(path, geoms):
    """Write a binary FBX (v7.4) document tools accept — Blender rejects
    ASCII FBX, so this is the shipped export format."""
    body, pos = b"", 27
    for node in _build_document(geoms):
        b, pos = _ser_node(node, pos)
        body += b
    body += b"\x00" * 13                  # top-level list terminator
    header = _MAGIC + struct.pack("<I", 7400)
    core = header + body
    footer = b"\x00" * 16
    footer += b"\x00" * ((16 - (len(core) + 16) % 16) % 16)
    footer += struct.pack("<I", 7400) + b"\x00" * 120 + _FOOT_MAGIC
    with open(path, "wb") as f:
        f.write(core + footer)
